---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(CHNOSZ)
data(thermo)
knitr::opts_chunk$set(echo = TRUE)
```

```{r fig.width=6, fig.height=6}
basis(c("Fe", "H2", "H2S", "H2O"), c("cr", "aq", "aq", "liq")) 
species(c("hematite", "pyrite", "pyrrhotite", "magnetite")) 
a <- affinity(H2S = c(-4, -1.5, 500), H2 = c(-6, -1, 500), T = 300, P = 700) 
diagram(a, fill = "terrain") 
title(main = "Fe-O-H-S") 
legend("bottomright", legend = c("300 °C, 700 bar")) 
```
```{r fig.width=12, fig.height=12}
par(mfrow = c(2, 2))
res <- 200
fill <- "terrain"

## K2O-Al2O3-SiO2-H2O, 25 degree C, 1 bar
## Steinmann et al., 1994 (http://ccm.geoscienceworld.org/content/42/2/197)
## Garrels and Christ, p. 361 (http://www.worldcat.org/oclc/517586)
## https://wwwbrr.cr.usgs.gov/projects/GWC_coupled/phreeqc/html/final-75.html
basis(c("Al+3", "pseudo-H4SiO4", "K+", "H2O", "H+", "O2"))
species(c("gibbsite", "muscovite", "kaolinite", "pyrophyllite", "K-feldspar"))
a <- affinity(H4SiO4 = c(-6, -2, res), `K+` = c(-3, 6, res))
diagram(a, ylab = ratlab("K+"), fill = fill, yline = 1.7)
title(main = syslab(c("K2O", "Al2O3", "SiO2", "H2O")))
legend("bottomleft", describe.property(c("T", "P"), c(25, 1)), bty = "n")
```

