# CHNOSZ diagrams =========

#' retrieve diagram data from affinity object
#' @param affinity object calculated by \link[CHNOSZ]{affinity}
#' @return tidy data frame with the plot areas
get_diagram_data <- function(affinity) {

  # get diagram object
  dout <- suppressMessages(diagram(affinity, plot.it = FALSE))

  # get area names
  if (affinity$property %in% c("G.basis", "logact.basis")){
    area <- rownames(affinity$basis)
  }else {
    area <- as.character(affinity$species$name)
  }

  if (length(area) == 0) {
    stop("no area names found", call. = FALSE)
  }

  # axes
  x_axis <- tibble(x = dout$vals[[1]], x_idx = seq_along(x))
  y_axis <- tibble(y = dout$vals[[2]], y_idx = seq_along(y))

  # contours
  contours <- dout$predominant %>%
    as.data.frame.table() %>% tbl_df() %>%
    rename(x_idx = Var1, y_idx = Var2, area_idx = Freq) %>%
    mutate_at(vars(x_idx, y_idx), as.numeric)

  # area labels
  areas <- tibble(
    area = !!area,
    area_idx = seq_along(area)
  )

  # combine everything
  contours %>%
    left_join(x_axis, by = "x_idx") %>%
    left_join(y_axis, by = "y_idx") %>%
    left_join(areas, by = "area_idx") %>%
    # find horizontal borders
    arrange(y_idx, x_idx) %>%
    mutate(border =
             c(FALSE, diff(area_idx) != 0 & diff(y_idx) == 0) |
             c(diff(area_idx) != 0 & diff(y_idx) == 0, FALSE)) %>%
    # find vertical borders
    arrange(x_idx, y_idx) %>%
    mutate(border = border |
             c(FALSE, diff(area_idx) != 0 & diff(x_idx) == 0) |
             c(diff(area_idx) != 0 & diff(x_idx) == 0, FALSE))
}

#' plot diagram data
#' @param diagram_data data frame generated by \code{get_diagram_data}
plot_diagram_data <- function(diagram_data) {
  diagram_data %>%
  ggplot() +
    aes(x = x, y = y, fill = area) +
    # area fills
    geom_raster() +
    # border lines
    geom_raster(data = function(df) filter(df, border), fill = "black") +
    # area labels
    geom_text(data = function(df) {
      df %>% group_by(area_idx, area) %>%
        summarize(x = mean(x), y = mean(y))
    }, mapping = aes(label = area, fill = NULL)) +
    # scales
    scale_fill_manual(
      values = diagram_data$area_idx %>% unique() %>% length() %>%
        terrain.colors()) +
    scale_x_continuous(expand = c(0,0)) +
    scale_y_continuous(expand = c(0,0)) +
    theme_bw()
}